Adicionado verificação de autenticação e autorização para GET /professores/{professor_id}
tauanesales/Sistema-PGCop-UFBA pull request #139
Opened 2024-07-17 20:03 UTC by alexgondim

…sores/{professor_id}. FIXES #80

## Descrição
FIXES #80

Esta PR adiciona autenticação ao endpoint GET /professores/{professor_id}, garantindo que apenas professores e coordenadores possam acessar as informações dos professores por ID.

### Critério de Aceite
- Verificado localmente 

## Que tipo de PR é este? (marque todos os aplicáveis)

- [ ] 🍕 Recurso (Feature)
- [ X] 🐛 Correção de Erro (Bugfix)
- [ ] 📝 Atualização de Documentação
- [ ] 🎨 Estilização
- [ X] 🧑‍💻 Refatoração de Código
- [ X] 🔥 Melhorias de Desempenho
- [ ] ✅ Testes (unitários/integração/e2e)
- [ ] 🤖 Compilação
- [ ] 🔁 Integração Contínua
- [ ] 📦 Tarefa (Nova versão)
- [ ] ⏩ Reverter

## Issues/Tickets e Documentos Relacionados

## Capturas de Tela/Gravações para Dispositivos Móveis e Desktop

## Passos para a QA

## Adicionado à Documentação?

## [opcional] Existem tarefas pós-implementação que precisamos realizar?

2024-07-18 15:47 UTC, alexgondim reviewed
FIXES #80

Esta PR adiciona autenticação ao endpoint GET /professores/{professor_id}, garantindo que apenas professores e coordenadores possam acessar as informações dos professores por ID.

### Critério de Aceite
- Verificado localmente conforme print abaixo.

2024-07-20 14:02 UTC, tauanesales requested changes

2024-07-20 14:02 UTC, tauanesales commented on src/api/entrypoints/professores/views.py
> +async def buscar_professor_por_id(professor_id: int, current_user: TokenData = Depends(get_current_user), repository=Depends(get_repo())):
Gostei da ideia de criar sua injeção de dependencia customizada.

2024-07-21 15:23 UTC, tauanesales commented on src/tests/unit/entrypoints/professores/test_professor_schema.py
> +
Não entendi. Favor remover comentários.

2024-07-21 15:56 UTC, closed without merging